{
 "title": "Curateur",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Timings",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(sl_curateur_flush_seconds_sum/sl_curateur_flush_seconds_count)",
     "legendFormat": "flush"
    },
    {
     "expr": "avg(sl_curateur_update_builds_seconds_sum/sl_curateur_update_builds_seconds_count)",
     "legendFormat": "update_builds"
    },
    {
     "expr": "avg(sl_curateur_trim_seconds_sum/sl_curateur_trim_seconds_count)",
     "legendFormat": "trim"
    },
    {
     "expr": "avg(sl_curateur_job_accounting_seconds_sum/sl_curateur_job_accounting_seconds_count)",
     "legendFormat": "job_accounting"
    },
    {
     "expr": "avg(sl_curateur_get_job_status_updates_seconds_sum/sl_curateur_get_job_status_updates_seconds_count)",
     "legendFormat": "get_job_status_updates"
    }
   ]
  },
  {
   "title": "Build / No Build",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sl_souschef_global_jobs_total" }
   ]
  },
  {
   "title": "States Pulled",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sl_curateur_states_total", "legendFormat": "states_total" }
   ]
  },
  {
   "title": "Builds to Flush",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sl_curateur_to_flush_total", "legendFormat": "to_flush" },
    {
     "expr": "sl_curateur_modified_builds_total",
     "legendFormat": "modified_builds"
    }
   ]
  },
  {
   "title": "Cached Builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sl_curateur_build_cache_total" }
   ]
  },
  {
   "title": "Builds Trimmed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sl_curateur_trimmed_total", "legendFormat": "trimmed" },
    { "expr": "sl_curateur_purged_total", "legendFormat": "purged" }
   ]
  },
  {
   "title": "Bucket Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sl_curateur_bucket_cache_total", "legendFormat": "bucket_cache" }
   ]
  },
  {
   "title": "Bucket Job Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sl_curateur_bucket_jobs_total", "legendFormat": "bucket_jobs" }
   ]
  },
  {
   "title": "Cleanup Loop",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(sl_curateur_find_errors_simple_seconds_sum/sl_curateur_find_errors_simple_seconds_count)",
     "legendFormat": "find_errors_simple_mean"
    },
    {
     "expr": "avg(sl_curateur_persist_errors_simple_seconds_sum/sl_curateur_persist_errors_simple_seconds_count)",
     "legendFormat": "persist_errors_simple_mean"
    },
    {
     "expr": "avg(sl_curateur_update_score_seconds_sum/sl_curateur_update_score_seconds_count)",
     "legendFormat": "update_score_mean"
    }
   ]
  },
  {
   "title": "Fixed Builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sl_curatuer_fixes_total", "legendFormat": "fixes" },
    { "expr": "sl_curateur_to_fix_total", "legendFormat": "to_fix" }
   ]
  },
  {
   "title": "To Check",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sl_curateur_to_check_total", "legendFormat": "to_check" },
    {
     "expr": "sl_curateur_janitor_queue_total",
     "legendFormat": "janitor_queue"
    }
   ]
  }
 ]
}