{
 "title": "plumber",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Claimed chefs souschef doesn't know about (5min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sl_plumber_terminate_claimed_chefs_stopped_total[5m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Unknown Chefs (5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sl_plumber_terminate_unknown_chefs_stopped_total[5m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Chef Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sl_punchclock_chef_state_total) by (state)"
    }
   ]
  },
  {
   "title": "Stop Long Running in-progress Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sl_plumber_long_in_progress_jobs_stopped_total",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cleanup Redis Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sl_plumber_cleanup_redis_jobs_status_jobs_total",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Max MEM Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(sum(container_memory_working_set_bytes{container_name=\"plumber\"}/container_spec_memory_limit_bytes{container_name=\"plumber\"}))"
    }
   ]
  },
  {
   "title": "Max CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(sum(sum(rate(container_cpu_usage_seconds_total{container_name=\"plumber\"}[$Interval])) / sum(container_spec_cpu_quota{container_name=\"plumber\"})) by (pod_name))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"plumber\"}[$Interval]))"
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=\"plumber\"})"
    }
   ]
  },
  {
   "title": "Plumber Blocked Eventloop",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sl_plumber_blocked_total_seconds_sum[1m])"
    },
    {
     "expr": "sl_plumber_blocked_total_seconds_sum/sl_plumber_blocked_total_seconds_count"
    }
   ]
  },
  {
   "title": "Tunnels Plumber Blocked Eventloop",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sl_tunnels_plumber_blocked_total_seconds_sum[1m])"
    },
    {
     "expr": "sl_tunnels_plumber_blocked_total_seconds_sum/sl_tunnels_plumber_blocked_total_seconds_count"
    }
   ]
  }
 ]
}