{
 "title": "Souschef",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Job Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sl_souschef_gauges_total{name=~\".*status.queued\"})",
     "legendFormat": "queued"
    },
    {
     "expr": "sum(sl_souschef_gauges_total{name=~\".*status.new\"})",
     "legendFormat": "new"
    },
    {
     "expr": "sum(sl_souschef_gauges_total{name=~\".*status.throttled-new\"})",
     "legendFormat": "throttled-new"
    },
    {
     "expr": "sum(sl_souschef_gauges_total{name=~\".*status.complete\"})",
     "legendFormat": "complete"
    },
    {
     "expr": "sum(sl_souschef_gauges_total{name=~\".*status.throttled-queued\"})",
     "legendFormat": "throttled-queued"
    },
    {
     "expr": "sum(sl_souschef_gauges_total{name=~\".*status.error\"})",
     "legendFormat": "error"
    },
    {
     "expr": "sum(sl_souschef_gauges_total{name=~\".*status.in_progress\"})",
     "legendFormat": "in_progress"
    }
   ]
  },
  {
   "title": "Job Assignment Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(sl_souschef_chefs_images_starved_total{image=~\"chef.*\"}[1m]))",
     "legendFormat": "Jobs waiting for chefs"
    },
    {
     "expr": "sum(max_over_time(sl_souschef_chefs_images_starved_total{image=~\"ichef.*\"}[1m]))",
     "legendFormat": "Mac Jobs waitings for ichefs"
    },
    {
     "expr": "sum(max_over_time(sl_souschef_chefs_images_starved_total{image=~\"lxchef.*\"}[1m]))",
     "legendFormat": "Jobs waiting fo lxchefs"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(sl_souschef_blocked_total_seconds_sum[10m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Dispatch Loop Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(sl_souschef_dispatch_new_jobs_seconds_sum[10m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sl_souschef_msgs_total{name=~\"resto.*\"}[1m]))",
     "legendFormat": "resto"
    },
    {
     "expr": "sum(rate(sl_souschef_msgs_total{name=~\"plumber.*\"}[1m]))",
     "legendFormat": "plumber"
    },
    {
     "expr": "sum(rate(sl_souschef_msgs_total{name=~\"chef.*\"}[1m]))",
     "legendFormat": "chef"
    },
    {
     "expr": "sum(rate(sl_souschef_msgs_total{name=~\"sushiboat.*\"}[1m]))",
     "legendFormat": "sushiboat"
    }
   ]
  },
  {
   "title": "File Uploads Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg(sl_souschef_jobs_statistics_total_sum{name=\"FileUploads\"}/sl_souschef_jobs_statistics_total_count{name=\"FileUploads\"})",
     "legendFormat": "FileUploads"
    }
   ]
  },
  {
   "title": "RamDB Flusher Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg(sl_souschef_ramdb_flush_doc_seconds_sum/sl_souschef_ramdb_flush_doc_seconds_count)",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "RamDB Flush Document Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sl_souschef_ramdb_flusher_docs_total[10m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Assigned Chef",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sl_souschef_gauges_total{name=\"jobs.assigned_chef\"})",
     "legendFormat": "assigned_chef"
    }
   ]
  },
  {
   "title": "Automation Backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sl_souschef_gauges_total{name=\"jobs.automation_backend.espresso\"})",
     "legendFormat": "espresso"
    },
    {
     "expr": "sum(sl_souschef_gauges_total{name=\"jobs.automation_backend.appium\"})",
     "legendFormat": "appium"
    },
    {
     "expr": "sum(sl_souschef_gauges_total{name=\"jobs.automation_backend.webdriver\"})",
     "legendFormat": "webdriver"
    }
   ]
  },
  {
   "title": "Unqueued due to stale queued",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sl_souschef_loops_stale_jobs{state=\"queued\"}"
    },
    {
     "expr": "sl_souschef_loops_stale_chefs{state=\"queued\"}"
    }
   ]
  },
  {
   "title": "Unqueued due to stale started",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sl_souschef_loops_stale_jobs{state=\"started\"}",
     "legendFormat": "jobs"
    },
    {
     "expr": "sl_souschef_loops_stale_chefs{state=\"started\"}",
     "legendFormat": "chefs"
    }
   ]
  }
 ]
}