{
 "title": "Sushiboat",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Se Command Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sl_sushiboat_requests_total{endpoint=\"/wd/hub\"}[1m]))"
    }
   ]
  },
  {
   "title": "New Session Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sl_sushiboat_events_counter{name=\"new_session_request\"}[1m]))"
    }
   ]
  },
  {
   "title": "Events rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sl_sushiboat_events_counter[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time spend in python method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(sl_sushiboat_method_exec_sum[1m])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}